languageCode = "en-us"
title = "Fisodd.Org"
baseurl = "https://www.fisodd.org/"
theme = "hugo-restructured"

sectionPagesMenu = "main"

[params]
  author = "Alexander Carlton"

  # Red Gradient
  hero_color = "white"
  hero_shade = "background: #870000; background: linear-gradient(to right, #190a05, #870000);" # https://uigradients.com/#TheStrain
  edge_shade = "background: #fdfcfb; background: linear-gradient(to bottom, #fdfcfb, #e2d1c3);" # https://webgradients.com -- 029 Everlasting Sky

