backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/img"
public_folder: "img"

collections:
  - name: "post"
    label: "Posts"
    folder: "content/post"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date",  name: "date",  widget: "datetime"}
      - {label: "Desc",  name: "description",  widget: "text"}
      - {label: "Body",  name: "body",  widget: "markdown"}
  - name: "rest"
    label: "Rests"
    folder: "content/rest"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date",  name: "date",  widget: "datetime"}
      - {label: "Desc",  name: "description",  widget: "text"}
      - {label: "Body",  name: "body",  widget: "markdown"}
